# -*- coding: utf-8 -*-
"""estimativa_vendas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v53cvNo0bYtHWE4uZN5kkJ6UW9mmNNWO

# **Estimativa de vendas utilizando Machine Learning**
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

"""**"Quanto possuir de estoque para suportar um investimento de R$ 75.000,00 em marketing?"**"""

base = pd.read_excel('/content/Investimento_x_Venda.xlsx')
base.head()

# Visualização gráfica das informações

plt.scatter(base['Investimento em marketing'], base['Venda Qtd'])
plt.show()

"""Descobrindo as vendas usando Machine Learning"""

from sklearn import linear_model

reg = linear_model.LinearRegression()
reg.fit(base['Investimento em marketing'].values.reshape(-1,1), base['Venda Qtd'])

# Coeficiênte angular
reg.coef_

# Coeficiênte Linear
reg.intercept_

plt.scatter(base['Investimento em marketing'],base['Venda Qtd'])
x = np.array(base['Investimento em marketing'])
y = reg.intercept_ + x*reg.coef_
plt.plot(x,y,'r')
plt.show()

reg.predict([[75]])

"""Passando a reta pelo ponto 75K"""

plt.scatter(base['Investimento em marketing'],base['Venda Qtd'])
plt.scatter(75,reg.predict([[75]])[0], color='k')
x = np.array(base['Investimento em marketing'])
y = reg.intercept_ + x*reg.coef_
plt.plot(x,y,'r')
plt.show()

# A quantidade de estoque que a empresa precisará ter para suprir as vendas com um investimento de R$ 75.000,00, é de 342.183 aproximadamente
reg.predict([[75]])